underline_button:
  default: "Underline"
  description:
    en: Enter the text for the title of the button in the composer.
underline_text:
  default: "Text"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.

Svg_icons: 
  type: 'list'
  list_type: 'compact'
  default: 'underline'
  description: 
    en: "Include FontAwesome 6 icon classes for each icon used in the list."
